customhost = "database-2.ckqbl1vsjxvg.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "liongpingting-employee"
customregion = "us-east-1"
